### ISSUE TITLE
findbuild problem

### ISSUE THREAD

**Issue by srwgin** [Meteorchestra/feh-simulator#2]
I found some heroes can not findbuilds
I use comparebuildsslots = consecutive-c-s

python battleSim.py findbuilds.txt Camus
Traceback (most recent call last):
File "battleSim.py", line 54, in 
slotresults = battle.calculateForEachBuild([slot])
File "D:\temp\0.new\feh-simulator-master\battle.py", line 1072, in calculateForEachBuild
results[skillsetString] = calculateForEachScenario(data.options["scenarios"])
File "D:\temp\0.new\feh-simulator-master\battle.py", line 1024, in calculateForEachScenario
statsForScenario = wrapWithTimer("calculate", calculate)
File "D:\temp\0.new\feh-simulator-master\battle.py", line 1047, in wrapWithTimer
return function(*args)
File "D:\temp\0.new\feh-simulator-master\battle.py", line 984, in calculate
"Damage Ratio": damageDealt/damageTaken,
ZeroDivisionError: division by zero

**Comment by srwgin** [comment]
D:\temp\0.new\feh-simulator-master>python battleSim.py findbuilds.txt Camus
Traceback (most recent call last):
  File "battleSim.py", line 54, in <module>
    slotresults = battle.calculateForEachBuild([slot])
  File "D:\temp\0.new\feh-simulator-master\battle.py", line 1072, in calculateForEachBuild
    results[skillsetString] = calculateForEachScenario(data.options["scenarios"])
  File "D:\temp\0.new\feh-simulator-master\battle.py", line 1024, in calculateForEachScenario
    statsForScenario = wrapWithTimer("calculate", calculate)
  File "D:\temp\0.new\feh-simulator-master\battle.py", line 1047, in wrapWithTimer
    return function(*args)
  File "D:\temp\0.new\feh-simulator-master\battle.py", line 984, in calculate
    "Damage Ratio": damageDealt/damageTaken,
ZeroDivisionError: division by zero

**Comment by Meteorchestra** [comment]
This will happen if you try to find the Damage Ratio of a Firesweep build for an offense-only scenario. Damage Ratio probably isn't the stat you want to be looking at there, but to make this a bit nicer, in any case where you take 0 damage in a scenario, the ratio will now be calculated as if you took 1 damage.
