### ISSUE TITLE
combatmode problem

### ISSUE THREAD

**Issue by srwgin** [Meteorchestra/feh-simulator#3]
the result has a little different between your software and https://kagerochart.com/damage-calc
then I found it is combatmode problem
when I set
combatmode = Duel
but the results is Gauntlet

if I set duel give me error
D:\temp\0.new\feh-simulator-master>battleSim.py
Traceback (most recent call last):
File "D:\temp\0.new\feh-simulator-master\battleSim.py", line 66, in 
battle.calculateForEachScenario(data.options["scenarios"])
File "D:\temp\0.new\feh-simulator-master\battle.py", line 1024, in calculateForEachScenario
statsForScenario = wrapWithTimer("calculate", calculate)
File "D:\temp\0.new\feh-simulator-master\battle.py", line 1047, in wrapWithTimer
return function(*args)
File "D:\temp\0.new\feh-simulator-master\battle.py", line 956, in calculate
fightResults.sort(key=sortByName)
File "D:\temp\0.new\feh-simulator-master\battle.py", line 929, in sortByName
return fightResult["enemy"].name
AttributeError: 'str' object has no attribute 'name'

**Comment by srwgin** [comment]
set Duel results is Gauntlet
if I set duel give me error
D:\temp\0.new\feh-simulator-master>battleSim.py
Traceback (most recent call last):
  File "D:\temp\0.new\feh-simulator-master\battleSim.py", line 66, in <module>
    battle.calculateForEachScenario(data.options["scenarios"])
  File "D:\temp\0.new\feh-simulator-master\battle.py", line 1024, in calculateForEachScenario
    statsForScenario = wrapWithTimer("calculate", calculate)
  File "D:\temp\0.new\feh-simulator-master\battle.py", line 1047, in wrapWithTimer
    return function(*args)
  File "D:\temp\0.new\feh-simulator-master\battle.py", line 956, in calculate
    fightResults.sort(key=sortByName)
  File "D:\temp\0.new\feh-simulator-master\battle.py", line 929, in sortByName
    return fightResult["enemy"].name
AttributeError: 'str' object has no attribute 'name'

**Comment by Meteorchestra** [comment]
Sorry about that! I changed the fight result structure a bit and it looks like I didn't update the duel mode function to sort the results accordingly. Should be fixed now.
